name: Check Broken Links

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, release-* ]
jobs:
  hugo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Run Hugo
        uses: crazy-max/ghaction-hugo@v3
        with:
          version: v0.119.0
          extended: true
          args: --cleanDestinationDir --minify --logLevel info
