name: Check Broken Links

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, release-* ]
jobs:
  hugo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
      - name: Build
        run: |
         npm install -D --save autoprefixer
         npm install -D --save postcss-cli
         npm install -D --save postcss
         hugo
      - name: Run Hugo
        uses: crazy-max/ghaction-hugo@v3
        with:
          version: v0.119.0
          extended: true
          args: --cleanDestinationDir --minify --logLevel info
