# Copyright (c) 2025 Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0

name: Update CSM Versions

on:
  workflow_dispatch:  # Allows manual trigger
  schedule:
    - cron: '0 0 * * 3'  # Runs every Wednesday at Midnight

jobs:
  csm-versions-update:
    uses: dell/common-github-actions/.github/workflows/csm-versions-update.yaml@main
    name: CSI Sidecars Update
    secrets: inherit
