name: Unit Test Action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, release-* ]
jobs:
  build-test:
      name: Build & Run Unit Test
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        working-directory: ./content/docs/deployment/csminstallationwizard/src/
        run: |
          npm install 
          npm test
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            ./content/docs/deployment/csminstallationwizard/src/reports/*.xml